<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Employees
[
<!ELEMENT Employees (Employee+)>
<!ELEMENT Employee (EmployeeNumber, Name, DepartmentNumber, Telephone, Email)>
<!ELEMENT EmployeeNumber (#PCDATA)>	
<!ELEMENT Name (#PCDATA)>
<!ELEMENT DepartmentNumber (#PCDATA)>
<!ELEMENT Telephone (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
]>



<Employees>
	<Employee>
		<EmployeeNumber>2305001</EmployeeNumber>
		<Name>Bhavi Mehta</Name>
		<DepartmentNumber>11</DepartmentNumber>
		<Telephone>8496923742</Telephone>
		<Email>bhavi.mmehta@xaviers.edu.in</Email>
	</Employee>
	<Employee>
		<EmployeeNumber>2305002</EmployeeNumber>
		<Name>Aaliya Dsouza</Name>
		<DepartmentNumber>12</DepartmentNumber>
		<Telephone>4374927492</Telephone>
		<Email>aaliya.dsouza@xaviers.edu.in</Email>
	</Employee>
	<Employee>
		<EmployeeNumber>2305003</EmployeeNumber>
		<Name>Diana Tanttra</Name>
		<DepartmentNumber>13</DepartmentNumber>
		<Telephone>8172461924</Telephone>
		<Email>diana.tanttra@xaviers.edu.in</Email>
	</Employee>
	<Employee>
		<EmployeeNumber>2305004</EmployeeNumber>
		<Name>Anuj Mehta</Name>
		<DepartmentNumber>11</DepartmentNumber>
		<Telephone>9741969311</Telephone>
		<Email>anuj.mehta@xaviers.edu.in</Email>
	</Employee>
	<Employee>
		<EmployeeNumber>2305005</EmployeeNumber>
		<Name>Arshia Dhole</Name>
		<DepartmentNumber>12</DepartmentNumber>
		<Telephone>9174982491</Telephone>
		<Email>arshia.dhole@xaviers.edu.in</Email>
	</Employee>
	<Employee>
		<EmployeeNumber>2305014</EmployeeNumber>
		<Name>Srajan Saldanha</Name>
		<DepartmentNumber>11</DepartmentNumber>
		<Telephone>7900168069</Telephone>
		<Email>srajan.saldanha@xaviers.edu.in</Email>
	</Employee>

	<Employee>
		<EmployeeNumber>2305015</EmployeeNumber>
		<Name>Aaron Pinto</Name>
		<DepartmentNumber>12</DepartmentNumber>
		<Telephone>8296205419</Telephone>
		<Email>aaron.pinto@xaviers.edu.in</Email>
	</Employee>

	<Employee>
		<EmployeeNumber>2305016</EmployeeNumber>
		<Name>Himani Kamerkar</Name>
		<DepartmentNumber>13</DepartmentNumber>
		<Telephone>9867493028</Telephone>
		<Email>himani.kamerkar@xaviers.edu</Email>
	</Employee>
</Employees>